Spree::PageContent.find_or_create_by! title: "Stores", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus, nulla ut commodo sagittis, sapien dui mattis dui, non pulvinar lorem felis nec erat.", slug: "user-store"
Spree::PageContent.find_or_create_by! title: "Manage Addresses", description: "Lorem Ipsum is simply dummy text.", slug: "address-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Add New", description: "", slug: "address-btn-label-new"
Spree::PageContent.find_or_create_by! title: "Primary Address", description: "", slug: "address-primary-heading"
Spree::PageContent.find_or_create_by! title: "Address", description: "", slug: "address-existing-heading"
Spree::PageContent.find_or_create_by! title: "Name", description: "", slug: "address-field-label-contact-name"
Spree::PageContent.find_or_create_by! title: "Name can't be blank", description: "", slug: "address-error-msg-contact-name"
Spree::PageContent.find_or_create_by! title: "Number", description: "", slug: "address-field-label-contact-number"
Spree::PageContent.find_or_create_by! title: "Number can't be blank", description: "", slug: "address-error-msg-contact-number"
Spree::PageContent.find_or_create_by! title: "Number is not valid", description: "", slug: "address-error-msg-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "Address", description: "", slug: "address-field-label-address-1"
Spree::PageContent.find_or_create_by! title: "Address can't be blank", description: "", slug: "address-error-msg-address-1"
Spree::PageContent.find_or_create_by! title: "Address Line 2", description: "", slug: "address-field-label-address-2"
Spree::PageContent.find_or_create_by! title: "Address Line 3", description: "", slug: "address-field-label-address-3"
Spree::PageContent.find_or_create_by! title: "Town/Suburb", description: "", slug: "address-field-label-town"
Spree::PageContent.find_or_create_by! title: "Town/Suburb can't be blank", description: "", slug: "address-error-msg-town"
Spree::PageContent.find_or_create_by! title: "State/Province", description: "", slug: "address-field-label-state"
Spree::PageContent.find_or_create_by! title: "State/Province can't be blank", description: "", slug: "address-error-msg-state"
Spree::PageContent.find_or_create_by! title: "Country ", description: "", slug: "address-field-label-country"
Spree::PageContent.find_or_create_by! title: "Country can't be blank", description: "", slug: "address-error-msg-country"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "address-btn-label-save"
Spree::PageContent.find_or_create_by! title: "Address successfully Updated", description: "", slug: "address-success-msg-save"
Spree::PageContent.find_or_create_by! title: "Primary", description: "", slug: "address-btn-label-primary"
Spree::PageContent.find_or_create_by! title: "Delete", description: "", slug: "address-btn-label-delete"
Spree::PageContent.find_or_create_by! title: "New Address", description: "", slug: "address-new-address-heading"
Spree::PageContent.find_or_create_by! title: "Name", description: "", slug: "address-field-label-new-contact-name"
Spree::PageContent.find_or_create_by! title: "Name can't be blank", description: "", slug: "address-error-msg-new-contact-name"
Spree::PageContent.find_or_create_by! title: "Number", description: "", slug: "address-field-label-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Number can't be blank", description: "", slug: "address-error-msg-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Number is not valid", description: "", slug: "address-error-msg-new-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "Address", description: "", slug: "address-field-label-new-address-1"
Spree::PageContent.find_or_create_by! title: "Address can't be blank", description: "", slug: "address-error-msg-new-address-1"
Spree::PageContent.find_or_create_by! title: "Street Address Line 2", description: "", slug: "address-field-label-new-address-2"
Spree::PageContent.find_or_create_by! title: "Street Address Line 3", description: "", slug: "address-field-label-new-address-3"
Spree::PageContent.find_or_create_by! title: "Town/Suburb", description: "", slug: "address-field-label-new-town"
Spree::PageContent.find_or_create_by! title: "Town/Suburb can't be blank", description: "", slug: "address-error-msg-new-town"
Spree::PageContent.find_or_create_by! title: "State/Province", description: "", slug: "address-field-label-new-state"
Spree::PageContent.find_or_create_by! title: "State/Province can't be blank", description: "", slug: "address-error-msg-new-satate"
Spree::PageContent.find_or_create_by! title: "Country ", description: "", slug: "address-field-label-new-country"
Spree::PageContent.find_or_create_by! title: "Country can't be blank", description: "", slug: "address-error-msg-new-country"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "address-btn-label-new-save"
Spree::PageContent.find_or_create_by! title: "Address successfully created", description: "", slug: "address-success-msg-new-save"
Spree::PageContent.find_or_create_by! title: "Address successfully deleted", description: "", slug: "address-success-msg-deleted"
Spree::PageContent.find_or_create_by! title: "Address successfully set as Primary", description: "", slug: "address-success-msg-primary"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "address-advertisement"
Spree::PageContent.find_or_create_by! title: "Welcome", description: "", slug: "user-messages-welcome"
Spree::PageContent.find_or_create_by! title: "Personal Information", description: "Lorem Ipsum is simply dummy text.", slug: "user-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "user-btn-label-save"
Spree::PageContent.find_or_create_by! title: "Information successfully updated", description: "", slug: "user-success-msg-save"
Spree::PageContent.find_or_create_by! title: "First Name *", description: "", slug: "user-field-label-first-name"
Spree::PageContent.find_or_create_by! title: "First Name can't be blank", description: "", slug: "user-error-msg-first-name"
Spree::PageContent.find_or_create_by! title: "Phone Number", description: "", slug: "user-field-label-phone-number"
Spree::PageContent.find_or_create_by! title: "Phone Number can't be blank", description: "", slug: "user-error-msg-phone-number"
Spree::PageContent.find_or_create_by! title: "Phone Number is not valid", description: "", slug: "user-error-msg-phone-number-formate"
Spree::PageContent.find_or_create_by! title: "Email *", description: "", slug: "user-field-label-email"
Spree::PageContent.find_or_create_by! title: "Email can't be blank", description: "", slug: "user-error-msg-email"
Spree::PageContent.find_or_create_by! title: "Email is not valid", description: "", slug: "user-error-msg-email-formate"
Spree::PageContent.find_or_create_by! title: "Confirm Email *", description: "", slug: "user-field-label-email-confirmation"
Spree::PageContent.find_or_create_by! title: "Confirm Email can't be blank", description: "", slug: "user-error-msg-email-confirmation"
Spree::PageContent.find_or_create_by! title: "Email Address is not matched .", description: "", slug: "user-error-msg-email-confirmation-matcher"
Spree::PageContent.find_or_create_by! title: "Password *", description: "", slug: "user-field-label-password"
Spree::PageContent.find_or_create_by! title: "Password can't be blank", description: "", slug: "user-error-msg-password"
Spree::PageContent.find_or_create_by! title: "Password is not valid", description: "", slug: "user-error-msg-password-formate"
Spree::PageContent.find_or_create_by! title: "Password Confirmation *", description: "", slug: "user-field-label-password-confirmation"
Spree::PageContent.find_or_create_by! title: "Password Confirmation can't be blank", description: "", slug: "user-error-msg-password-confirmation"
Spree::PageContent.find_or_create_by! title: "Select Your Country ", description: "", slug: "user-field-label-country"
Spree::PageContent.find_or_create_by! title: "Last Name *", description: "", slug: "user-field-label-last-name"
Spree::PageContent.find_or_create_by! title: "Last Name can't be blank", description: "", slug: "user-error-msg-last-name"
Spree::PageContent.find_or_create_by! title: "Day of Birth", description: "", slug: "user-field-label-birth-date"
Spree::PageContent.find_or_create_by! title: "Date of Birth can't be blank", description: "", slug: "user-error-msg-birth-date"
Spree::PageContent.find_or_create_by! title: "Month of Birth", description: "", slug: "user-field-label-birth-month"
Spree::PageContent.find_or_create_by! title: "Month of Birth can't be blank", description: "", slug: "user-error-msg-birth-month"
Spree::PageContent.find_or_create_by! title: "Measurement Information", description: "Lorem Ipsum is simply dummy text.", slug: "user-main-msr-heading-desc"
Spree::PageContent.find_or_create_by! title: "Head", description: "", slug: "user-field-msr-label-head"
Spree::PageContent.find_or_create_by! title: "Shoulder Left", description: "", slug: "user-field-msr-shld-lft"
Spree::PageContent.find_or_create_by! title: "Shoulder Left must be 2 decimal", description: "", slug: "user-error-msg-msr-shld-lft-formate"
Spree::PageContent.find_or_create_by! title: "Shoulder Right", description: "", slug: "user-field-msr-shld-rgt"
Spree::PageContent.find_or_create_by! title: "Left Arm", description: "", slug: "user-field-msr-label-lft-arm"
Spree::PageContent.find_or_create_by! title: "Save Measurement ", description: "", slug: "user-btn-msr-label-save"
Spree::PageContent.find_or_create_by! title: "Measurement Information successfully updated", description: "", slug: "user-msr-success-msg-save"
Spree::PageContent.find_or_create_by! title: "Personal Information", description: "", slug: "profile-nav-txt-personal-info"
Spree::PageContent.find_or_create_by! title: "My Addresses", description: "", slug: "profile-nav-txt-addresses"
Spree::PageContent.find_or_create_by! title: "My Orders", description: "", slug: "profile-nav-txt-orders"
Spree::PageContent.find_or_create_by! title: "My Wishlist", description: "", slug: "profile-nav-txt-wishlist"
Spree::PageContent.find_or_create_by! title: "My Reviews", description: "", slug: "profile-nav-txt-reviews"
Spree::PageContent.find_or_create_by! title: "My Stores", description: "", slug: "profile-nav-txt-stores"
Spree::PageContent.find_or_create_by! title: "My Settings", description: "", slug: "profile-nav-txt-settings"
Spree::PageContent.find_or_create_by! title: "My Messages", description: "", slug: "profile-nav-txt-messages"
Spree::PageContent.find_or_create_by! title: "Support Centre", description: "", slug: "profile-nav-txt-support-centre"
Spree::PageContent.find_or_create_by! title: "Logout", description: "", slug: "profile-nav-txt-logout"
Spree::PageContent.find_or_create_by! title: "Logout Successfully", description: "", slug: "profile-nav-txt-msg-success-logout"
Spree::PageContent.find_or_create_by! title: "Orders", description: "Lorem Ipsum is simply dummy text.", slug: "order-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Order Details", description: "", slug: "order-sub-heading-order-details"
Spree::PageContent.find_or_create_by! title: "Purchased on", description: "", slug: "order-purchased-on-label"
Spree::PageContent.find_or_create_by! title: "Personalised", description: "", slug: "order-personalised-label"
Spree::PageContent.find_or_create_by! title: "Payment method", description: "", slug: "order-payment-method-label"
Spree::PageContent.find_or_create_by! title: "Shiping Details", description: "", slug: "order-sub-heading-shiping-details"
Spree::PageContent.find_or_create_by! title: "Order Summary", description: "", slug: "order-sub-heading-order-summary"
Spree::PageContent.find_or_create_by! title: "OFF", description: "", slug: "order-sale-off-label"
Spree::PageContent.find_or_create_by! title: "Review", description: "", slug: "order-review-button-label"
Spree::PageContent.find_or_create_by! title: "My Review", description: "", slug: "order-my-review-button-label"
Spree::PageContent.find_or_create_by! title: "Download Invoice", description: "", slug: "order-download-invoice-button-label"
Spree::PageContent.find_or_create_by! title: "Contact Store", description: "", slug: "order-contact-store-button-label"
Spree::PageContent.find_or_create_by! title: "Request Return", description: "", slug: "order-request-return-button-label"
Spree::PageContent.find_or_create_by! title: "View Messages", description: "", slug: "order-view-messages-button-label"
Spree::PageContent.find_or_create_by! title: "Create Product Review", description: "", slug: "order-create-product-review-label"
Spree::PageContent.find_or_create_by! title: "Overall Star Rating", description: "", slug: "order-overall-star-rating-review-label"
Spree::PageContent.find_or_create_by! title: "Add Review", description: "", slug: "order-add-review-button-label"
Spree::PageContent.find_or_create_by! title: "Cancel", description: "", slug: "order-cancel-review-button-label"
Spree::PageContent.find_or_create_by! title: "Product Review", description: "", slug: "order-product-review-heading"
Spree::PageContent.find_or_create_by! title: "Product Name", description: "", slug: "order-my-review-product-name"
Spree::PageContent.find_or_create_by! title: "Review Date", description: "", slug: "order-my-review-date"
Spree::PageContent.find_or_create_by! title: "Close", description: "", slug: "order-my-review-close"
Spree::PageContent.find_or_create_by! title: "Items", description: "", slug: "order-detail-items"
Spree::PageContent.find_or_create_by! title: "Shipping", description: "", slug: "order-summary-shipping-label"
Spree::PageContent.find_or_create_by! title: "Product Total:", description: "", slug: "order-summary-product-total-label"
Spree::PageContent.find_or_create_by! title: "Purchased from", description: "", slug: "order-number-purchased-from-label"
Spree::PageContent.find_or_create_by! title: "Order Received", description: "", slug: "order-status-received-label"
Spree::PageContent.find_or_create_by! title: "Order in Progress", description: "", slug: "order-status-in-progress-label"
Spree::PageContent.find_or_create_by! title: "Order Delivered", description: "", slug: "order-status-delivered-label"
Spree::PageContent.find_or_create_by! title: "Shiped On", description: "", slug: "order-shiped-on-label"
Spree::PageContent.find_or_create_by! title: "Tracking Number", description: "", slug: "order-tracking-number-label"
Spree::PageContent.find_or_create_by! title: "Currency", description: "", slug: "order-currency-label"
Spree::PageContent.find_or_create_by! title: "Discount", description: "", slug: "order-discount-label"
Spree::PageContent.find_or_create_by! title: "Store Credit", description: "", slug: "order-store-credit-label"
Spree::PageContent.find_or_create_by! title: "Gift Card", description: "", slug: "order-gift-card-label"
Spree::PageContent.find_or_create_by! title: "VAT", description: "", slug: "order-vat-label"
Spree::PageContent.find_or_create_by! title: "VAT", description: "", slug: "order-vat-total-label"
Spree::PageContent.find_or_create_by! title: "Order Total:", description: "", slug: "order-total-inc-vat-label"
Spree::PageContent.find_or_create_by! title: "WishList", description: "Lorem Ipsum is simply dummy text.", slug: "wishlist-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "OFF", description: "", slug: "wishlist-label-off"
Spree::PageContent.find_or_create_by! title: "Add to Cart", description: "", slug: "wishlist-btn-label-add-to-cart"
Spree::PageContent.find_or_create_by! title: "Delete", description: "", slug: "wishlist-btn-label-delete"
Spree::PageContent.find_or_create_by! title: "Some Error occured while wishlist product deletion", description: "", slug: "wishlist-error-msg-delete"
Spree::PageContent.find_or_create_by! title: "Product is successfully deleted from wishlist", description: "", slug: "wishlist-success-msg-delete"
Spree::PageContent.find_or_create_by! title: "Currently unable to add", description: "", slug: "wishlist-error-before-msg-add"
Spree::PageContent.find_or_create_by! title: " to your wishlist.  Please try again", description: "", slug: "wishlist-error-after-msg-add"
Spree::PageContent.find_or_create_by! title: "is successfully added to your Wishlist.", description: "", slug: "wishlist-success-msg-add"
Spree::PageContent.find_or_create_by! title: "Temporarily out of Stock", description: "", slug: "wishlist-label-out-off-stock"
Spree::PageContent.find_or_create_by! title: "In Stock", description: "", slug: "wishlist-label-in-stock"
Spree::PageContent.find_or_create_by! title: "Load More", description: "", slug: "wishlist-btn-label-load-more"
Spree::PageContent.find_or_create_by! title: "Back To Top", description: "", slug: "wishlist-btn-label-top"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "wishlist-label-advertisement"
Spree::PageContent.find_or_create_by! title: "Search for products, shops and more", description: "", slug: "header-label-search"
Spree::PageContent.find_or_create_by! title: "Login", description: "", slug: "header-label-login"
Spree::PageContent.find_or_create_by! title: "Register", description: "", slug: "header-label-register"
Spree::PageContent.find_or_create_by! title: "Language", description: "", slug: "header-label-language"
Spree::PageContent.find_or_create_by! title: "Article 1", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magn", slug: "home-article-1"
Spree::PageContent.find_or_create_by! title: "Article 2", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magn", slug: "home-article-2"
Spree::PageContent.find_or_create_by! title: "Article 3", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magn", slug: "home-article-3"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "home-advertisement"
Spree::PageContent.find_or_create_by! title: "Things You Might Want To Know", description: "", slug: "footer-main-head-desc"
Spree::PageContent.find_or_create_by! title: "Let's Connect", description: "", slug: "footer-sec-connect"
Spree::PageContent.find_or_create_by! title: "Register My Store", description: "", slug: "footer-sec-lnk-register-store"
Spree::PageContent.find_or_create_by! title: "About Us", description: "", slug: "footer-sec-lnk-about-us"
Spree::PageContent.find_or_create_by! title: "Gift Cards", description: "", slug: "footer-sec-lnk-gift-cards"
Spree::PageContent.find_or_create_by! title: "Personal Service", description: "", slug: "footer-sec-lnk-personal-service"
Spree::PageContent.find_or_create_by! title: "Delivery", description: "", slug: "footer-sec-lnk-delivery"
Spree::PageContent.find_or_create_by! title: "Exchanges and Returns", description: "", slug: "footer-sec-lnk-exchange-returns"
Spree::PageContent.find_or_create_by! title: "Security", description: "", slug: "footer-sec-lnk-security"
Spree::PageContent.find_or_create_by! title: "Terms and Conditions", description: "", slug: "footer-sec-lnk-terms"
Spree::PageContent.find_or_create_by! title: "Privacy Policy", description: "", slug: "footer-sec-lnk-privacy"
Spree::PageContent.find_or_create_by! title: "Cookie Policy", description: "", slug: "footer-sec-lnk-cookie"
Spree::PageContent.find_or_create_by! title: "Support", description: "", slug: "footer-sec-lnk-support"
Spree::PageContent.find_or_create_by! title: "FAQ's", description: "", slug: "footer-sec-lnk-faqs"
Spree::PageContent.find_or_create_by! title: "Clothes", description: "", slug: "header-tabs-label-clothes"
Spree::PageContent.find_or_create_by! title: "Home", description: "", slug: "header-tabs-label-home"
Spree::PageContent.find_or_create_by! title: "Stores", description: "", slug: "header-tabs-label-stores"
Spree::PageContent.find_or_create_by! title: "Categories", description: "", slug: "header-tabs-label-categories"
Spree::PageContent.find_or_create_by! title: "Sale", description: "", slug: "header-tabs-label-sale"
Spree::PageContent.find_or_create_by! title: "We Specialise In", description: "", slug: "store-dtl-heading-speciality"
Spree::PageContent.find_or_create_by! title: "You Can Find Us At:", description: "", slug: "store-dtl-heading-find-us"
Spree::PageContent.find_or_create_by! title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", description: "", slug: "store-dtl-heading-follow-inst"
Spree::PageContent.find_or_create_by! title: "Top Designs as Selected By The Designer", description: "", slug: "store-dtl-heading-top-design"
Spree::PageContent.find_or_create_by! title: "View Entire Range", description: "", slug: "store-dtl-heading-view-entire"
Spree::PageContent.find_or_create_by! title: "Follow", description: "", slug: "store-dtl-heading-follow"
Spree::PageContent.find_or_create_by! title: "Unfollow", description: "", slug: "store-dtl-heading-unfollow"
Spree::PageContent.find_or_create_by! title: "An Introduction", description: "", slug: "store-dtl-heading-introduction"
Spree::PageContent.find_or_create_by! title: "Articles Featuring The Designer", description: "", slug: "store-dtl-heading-article"
Spree::PageContent.find_or_create_by! title: "Opening Hours:", description: "", slug: "store-dtl-time-opn_hrs"
Spree::PageContent.find_or_create_by! title: "Mon", description: "", slug: "store-dtl-time-mon"
Spree::PageContent.find_or_create_by! title: "Tue", description: "", slug: "store-dtl-time-tue"
Spree::PageContent.find_or_create_by! title: "Wed", description: "", slug: "store-dtl-time-wed"
Spree::PageContent.find_or_create_by! title: "Thu", description: "", slug: "store-dtl-time-thu"
Spree::PageContent.find_or_create_by! title: "Fri", description: "", slug: "store-dtl-time-fri"
Spree::PageContent.find_or_create_by! title: "Sat", description: "", slug: "store-dtl-time-sat"
Spree::PageContent.find_or_create_by! title: "Sun", description: "", slug: "store-dtl-time-sun"
Spree::PageContent.find_or_create_by! title: "Public Holidays", description: "", slug: "store-dtl-time-pub-holiday"
Spree::PageContent.find_or_create_by! title: "From", description: "", slug: "product-label-from"
Spree::PageContent.find_or_create_by! title: "More Colours Available", description: "", slug: "product-label-more-colors"
Spree::PageContent.find_or_create_by! title: "Categories", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt", slug: "home-label-categories-head_desc"
Spree::PageContent.find_or_create_by! title: "Latest on Black-Line", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt", slug: "home-label-latest-products"
Spree::PageContent.find_or_create_by! title: "Visit our stores", description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt", slug: "home-label-stores-heading-desc"
Spree::PageContent.find_or_create_by! title: "No Store(s) Found", description: "", slug: "general-label-no-stores"
Spree::PageContent.find_or_create_by! title: "No Product(s) Found", description: "", slug: "general-label-no-products"
Spree::PageContent.find_or_create_by! title: "Are you sure", description: "", slug: "general-label-sure?"
Spree::PageContent.find_or_create_by! title: "Out of Stock", description: "", slug: "general-label-out-of-stock"
Spree::PageContent.find_or_create_by! title: "Add to cart", description: "", slug: "general-label-add-to-cart"

Spree::PageContent.find_or_create_by! title: "Check Out", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus, nulla ut commodo sagittis, sapien dui mattis dui, non pulvinar lorem felis nec erat.", slug: "checkout-page-checkout-steps"
Spree::PageContent.find_or_create_by! title: "Check Out", description: "Our Designers can’t wait to get started on your custom Abaya(s).  All you need to do is confirm your address (Shipping and Billing) and select Finalise Order.", slug: "checkout-page-custom-order"
Spree::PageContent.find_or_create_by! title: "Check Out", description: "Nearly there, to get your Abaya(s) all you need to do is confirm your address (Shipping and Billing) and select Finalise Order.", slug: "checkout-page-non-custom"
Spree::PageContent.find_or_create_by! title: "Shopping Cart", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus, nulla ut commodo sagittis, sapien dui mattis dui, non pulvinar lorem felis nec erat.", slug: "checkout-page-cart"
Spree::PageContent.find_or_create_by! title: "Thank you for your purchase", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus, nulla ut commodo sagittis, sapien dui mattis dui, non pulvinar lorem felis nec erat.", slug: "checkout-page-final-order"
Spree::PageContent.find_or_create_by! title: "Thank you for your purchase", description: "Thank you for your order.  Our designers can’t wait to get started on your Abaya(s). We have sent you an email confirming all the details.", slug: "final-order-custom"
Spree::PageContent.find_or_create_by! title: "Thank you for your purchase", description: "Thank you for your order, your Abaya(s) will be with you soon.  We have sent you an email confirming all the details.", slug: "final-order-non-custom"

Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "checkout-page-steps-advertisement"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "checkout-page-cart-advertisement"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "checkout-page-final-order-advertisement"
Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "search-global-advertisement"

Spree::PageContent.find_or_create_by! title: "Stores", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus, nulla ut commodo sagittis, sapien dui mattis dui, non pulvinar lorem felis nec erat.", slug: "user-store"