Spree::PageContent.find_or_create_by! title: "Address", description: "Lorem Ipsum is simply dummy text.", slug: "address-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Add New", description: "", slug: "address-btn-label-new"
Spree::PageContent.find_or_create_by! title: "Primary Address", description: "", slug: "address-primary-heading"
Spree::PageContent.find_or_create_by! title: "Address", description: "", slug: "address-existing-heading"

Spree::PageContent.find_or_create_by! title: "Contact Name", description: "", slug: "address-field-label-contact-name"
Spree::PageContent.find_or_create_by! title: "Contact Name can't be blank", description: "", slug: "address-error-msg-contact-name"
Spree::PageContent.find_or_create_by! title: "Contact Number", description: "", slug: "address-field-label-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number can't be blank", description: "", slug: "address-error-msg-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number is not valid", description: "", slug: "address-error-msg-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "Street Address Line 1", description: "", slug: "address-field-label-address-1"
Spree::PageContent.find_or_create_by! title: "Address Line 1 can't be blank", description: "", slug: "address-error-msg-address-1"
Spree::PageContent.find_or_create_by! title: "Street Address Line 2", description: "", slug: "address-field-label-address-2"
Spree::PageContent.find_or_create_by! title: "Street Address Line 3", description: "", slug: "address-field-label-address-3"
Spree::PageContent.find_or_create_by! title: "Town/Suburb", description: "", slug: "address-field-label-town"
Spree::PageContent.find_or_create_by! title: "Town/Suburb can't be blank", description: "", slug: "address-error-msg-town"
Spree::PageContent.find_or_create_by! title: "State/Province", description: "", slug: "address-field-label-state"
Spree::PageContent.find_or_create_by! title: "State/Province can't be blank", description: "", slug: "address-error-msg-state"
Spree::PageContent.find_or_create_by! title: "Country ", description: "", slug: "address-field-label-country"
Spree::PageContent.find_or_create_by! title: "Country can't be blank", description: "", slug: "address-error-msg-country"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "address-btn-label-save"
Spree::PageContent.find_or_create_by! title: "Address successfully Updated", description: "", slug: "address-success-msg-save"
Spree::PageContent.find_or_create_by! title: "Primary", description: "", slug: "address-btn-label-primary"
Spree::PageContent.find_or_create_by! title: "Delete", description: "", slug: "address-btn-label-delete"
Spree::PageContent.find_or_create_by! title: "New Address", description: "", slug: "address-new-address-heading"
Spree::PageContent.find_or_create_by! title: "New Contact Name", description: "", slug: "address-field-label-new-contact-name"
Spree::PageContent.find_or_create_by! title: "New Contact Name can't be blank", description: "", slug: "address-error-msg-new-contact-name"
Spree::PageContent.find_or_create_by! title: "New Contact Number", description: "", slug: "address-field-label-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number can't be blank", description: "", slug: "address-error-msg-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number is not valid", description: "", slug: "address-error-msg-new-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 1", description: "", slug: "address-field-label-new-address-1"
Spree::PageContent.find_or_create_by! title: "New Address Line 1 can't be blank", description: "", slug: "address-error-msg-new-address-1"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 2", description: "", slug: "address-field-label-new-address-2"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 3", description: "", slug: "address-field-label-new-address-3"
Spree::PageContent.find_or_create_by! title: "New Town/Suburb", description: "", slug: "address-field-label-new-town"
Spree::PageContent.find_or_create_by! title: "New Town/Suburb can't be blank", description: "", slug: "address-error-msg-new-town"
Spree::PageContent.find_or_create_by! title: "New State/Province", description: "", slug: "address-field-label-new-state"
Spree::PageContent.find_or_create_by! title: "New State/Province can't be blank", description: "", slug: "address-error-msg-new-satate"
Spree::PageContent.find_or_create_by! title: "New Country ", description: "", slug: "address-field-label-new-country"
Spree::PageContent.find_or_create_by! title: "New Country can't be blank", description: "", slug: "address-error-msg-new-country"
Spree::PageContent.find_or_create_by! title: "New Save", description: "", slug: "address-btn-label-new-save"
Spree::PageContent.find_or_create_by! title: "New Address successfully created", description: "", slug: "address-success-msg-new-save"
Spree::PageContent.find_or_create_by! title: "Address successfully deleted", description: "", slug: "address-success-msg-deleted"
Spree::PageContent.find_or_create_by! title: "Address successfully set as Primary", description: "", slug: "address-success-msg-primary"

Spree::PageContent.find_or_create_by! title: "Welcome", description: "", slug: "user-messages-welcome"
Spree::PageContent.find_or_create_by! title: "Personal Information", description: "Lorem Ipsum is simply dummy text.", slug: "user-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "user-btn-label-save"
Spree::PageContent.find_or_create_by! title: "Information successfully updated", description: "", slug: "user-success-msg-save"
Spree::PageContent.find_or_create_by! title: "First Name", description: "", slug: "user-field-label-first-name"
Spree::PageContent.find_or_create_by! title: "First Name can't be blank", description: "", slug: "user-error-msg-first-name"
Spree::PageContent.find_or_create_by! title: "Phone Number", description: "", slug: "user-field-label-phone-number"
Spree::PageContent.find_or_create_by! title: "Phone Number can't be blank", description: "", slug: "user-error-msg-phone-number"
Spree::PageContent.find_or_create_by! title: "Phone Number is not valid", description: "", slug: "user-error-msg-phone-number-formate"
Spree::PageContent.find_or_create_by! title: "Email", description: "", slug: "user-field-label-email"
Spree::PageContent.find_or_create_by! title: "Email can't be blank", description: "", slug: "user-error-msg-email"
Spree::PageContent.find_or_create_by! title: "Email is not valid", description: "", slug: "user-error-msg-email-formate"
Spree::PageContent.find_or_create_by! title: "Confirm Email Address*", description: "", slug: "user-field-label-email-confirmation"
Spree::PageContent.find_or_create_by! title: "Confirm Email can't be blank", description: "", slug: "user-error-msg-email-confirmation"
Spree::PageContent.find_or_create_by! title: "Email Address is not matched .", description: "", slug: "user-error-msg-email-confirmation-matcher"
Spree::PageContent.find_or_create_by! title: "Password*", description: "", slug: "user-field-label-password"
Spree::PageContent.find_or_create_by! title: "Password can't be blank", description: "", slug: "user-error-msg-password"
Spree::PageContent.find_or_create_by! title: "Password is not valid", description: "", slug: "user-error-msg-password-formate"
Spree::PageContent.find_or_create_by! title: "Password Confirmation *", description: "", slug: "user-field-label-password-confirmation"
Spree::PageContent.find_or_create_by! title: "Password Confirmation can't be blank", description: "", slug: "user-error-msg-password-confirmation"
Spree::PageContent.find_or_create_by! title: "Select Your Country ", description: "", slug: "user-field-label-country"

Spree::PageContent.find_or_create_by! title: "Last Name", description: "", slug: "user-field-label-last-name"
Spree::PageContent.find_or_create_by! title: "Last Name can't be blank", description: "", slug: "user-error-msg-last-name"
Spree::PageContent.find_or_create_by! title: "Date of Birth", description: "", slug: "user-field-label-birth-date"
Spree::PageContent.find_or_create_by! title: "Date of Birth can't be blank", description: "", slug: "user-error-msg-birth-date"
Spree::PageContent.find_or_create_by! title: "Month of Birth", description: "", slug: "user-field-label-birth-month"
Spree::PageContent.find_or_create_by! title: "Month of Birth can't be blank", description: "", slug: "user-error-msg-birth-month"
Spree::PageContent.find_or_create_by! title: "Measurement Information", description: "Lorem Ipsum is simply dummy text.", slug: "user-main-msr-heading-desc"
Spree::PageContent.find_or_create_by! title: "Head", description: "", slug: "user-field-msr-label-head"
Spree::PageContent.find_or_create_by! title: "Shoulder Left", description: "", slug: "user-field-msr-shld-lft"
Spree::PageContent.find_or_create_by! title: "Shoulder Left must be 2 decimal", description: "", slug: "user-error-msg-msr-shld-lft-formate"
Spree::PageContent.find_or_create_by! title: "Shoulder Right", description: "", slug: "user-field-msr-shld-rgt"
Spree::PageContent.find_or_create_by! title: "Left Arm", description: "", slug: "user-field-msr-label-lft-arm"
Spree::PageContent.find_or_create_by! title: "Save Measurement ", description: "", slug: "user-btn-msr-label-save"
Spree::PageContent.find_or_create_by! title: "Measurement Information successfully updated", description: "", slug: "user-msr-success-msg-save"
Spree::PageContent.find_or_create_by! title: "Personal Information", description: "", slug: "profile-nav-txt-personal-info"
Spree::PageContent.find_or_create_by! title: "My Addresses", description: "", slug: "profile-nav-txt-addresses"
Spree::PageContent.find_or_create_by! title: "My Orders", description: "", slug: "profile-nav-txt-orders"
Spree::PageContent.find_or_create_by! title: "My Wishlist", description: "", slug: "profile-nav-txt-wishlist"
Spree::PageContent.find_or_create_by! title: "My Reviews", description: "", slug: "profile-nav-txt-reviews"
Spree::PageContent.find_or_create_by! title: "My Stores", description: "", slug: "profile-nav-txt-stores"
Spree::PageContent.find_or_create_by! title: "My Settings", description: "", slug: "profile-nav-txt-settings"
Spree::PageContent.find_or_create_by! title: "My Messages", description: "", slug: "profile-nav-txt-messages"
Spree::PageContent.find_or_create_by! title: "Support Centre", description: "", slug: "profile-nav-txt-support-centre"
Spree::PageContent.find_or_create_by! title: "Logout", description: "", slug: "profile-nav-txt-logout"
Spree::PageContent.find_or_create_by! title: "Logout Successfully", description: "", slug: "profile-nav-txt-msg-success-logout"

Spree::PageContent.find_or_create_by! title: "Orders", description: "Lorem Ipsum is simply dummy text.", slug: "order-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Order Details", description: "", slug: "order-sub-heading-order-details"
Spree::PageContent.find_or_create_by! title: "Purchased on", description: "", slug: "order-purchased-on-label"
Spree::PageContent.find_or_create_by! title: "Personalised", description: "", slug: "order-personalised-label"
Spree::PageContent.find_or_create_by! title: "Payment method", description: "", slug: "order-payment-method-label"
Spree::PageContent.find_or_create_by! title: "Shiping Details", description: "", slug: "order-sub-heading-shiping-details"
Spree::PageContent.find_or_create_by! title: "Order Summary", description: "", slug: "order-sub-heading-order-summary"
Spree::PageContent.find_or_create_by! title: "OFF", description: "", slug: "order-sale-off-label"
Spree::PageContent.find_or_create_by! title: "Review", description: "", slug: "order-review-button-label"
Spree::PageContent.find_or_create_by! title: "My Review", description: "", slug: "order-my-review-button-label"
Spree::PageContent.find_or_create_by! title: "Download Invoice", description: "", slug: "order-download-invoice-button-label"
Spree::PageContent.find_or_create_by! title: "Contact Store", description: "", slug: "order-contact-store-button-label"
Spree::PageContent.find_or_create_by! title: "Request Return", description: "", slug: "order-request-return-button-label"
Spree::PageContent.find_or_create_by! title: "View Messages", description: "", slug: "order-view-messages-button-label"
Spree::PageContent.find_or_create_by! title: "Create Product Review", description: "", slug: "order-create-product-review-label"
Spree::PageContent.find_or_create_by! title: "Overall Star Rating", description: "", slug: "order-overall-star-rating-review-label"
Spree::PageContent.find_or_create_by! title: "Add Review", description: "", slug: "order-add-review-button-label"
Spree::PageContent.find_or_create_by! title: "Cancel", description: "", slug: "order-cancel-review-button-label"
Spree::PageContent.find_or_create_by! title: "Product Review", description: "", slug: "order-product-review-heading"
Spree::PageContent.find_or_create_by! title: "Product Name", description: "", slug: "order-my-review-product-name"
Spree::PageContent.find_or_create_by! title: "Review Date", description: "", slug: "order-my-review-date"
Spree::PageContent.find_or_create_by! title: "Close", description: "", slug: "order-my-review-close"
Spree::PageContent.find_or_create_by! title: "Items", description: "", slug: "order-detail-items"
Spree::PageContent.find_or_create_by! title: "Shipping", description: "", slug: "order-summary-shipping-label"
Spree::PageContent.find_or_create_by! title: "Purchased from", description: "", slug: "order-number-purchased-from-label"
Spree::PageContent.find_or_create_by! title: "Order Received", description: "", slug: "order-status-received-label"
Spree::PageContent.find_or_create_by! title: "Order in Progress", description: "", slug: "order-status-in-progress-label"
Spree::PageContent.find_or_create_by! title: "Order Delivered", description: "", slug: "order-status-delivered-label"
Spree::PageContent.find_or_create_by! title: "Shiped On", description: "", slug: "order-shiped-on-label"
Spree::PageContent.find_or_create_by! title: "Tracking Number", description: "", slug: "order-tracking-number-label"


Spree::PageContent.find_or_create_by! title: "WishList", description: "Lorem Ipsum is simply dummy text.", slug: "wishlist-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "OFF", description: "", slug: "wishlist-label-off"
Spree::PageContent.find_or_create_by! title: "Add to Cart", description: "", slug: "wishlist-btn-label-add-to-cart"
Spree::PageContent.find_or_create_by! title: "Delete", description: "", slug: "wishlist-btn-label-delete"
Spree::PageContent.find_or_create_by! title: "Some Error occured while wishlist product deletion", description: "", slug: "wishlist-error-msg-delete"
Spree::PageContent.find_or_create_by! title: "Product is successfully deleted from wishlist", description: "", slug: "wishlist-success-msg-delete"
Spree::PageContent.find_or_create_by! title: "Temporarily out of Stock", description: "", slug: "wishlist-label-out-off-stock"
Spree::PageContent.find_or_create_by! title: "In Stock", description: "", slug: "wishlist-label-in-stock"


Spree::PageContent.find_or_create_by! title: "Load More", description: "", slug: "wishlist-btn-label-load-more"
Spree::PageContent.find_or_create_by! title: "Back To Top", description: "", slug: "wishlist-btn-label-top"



Spree::PageContent.find_or_create_by! title: "Advertisement", description: "", slug: "wishlist-label-advertisement"
