Spree::PageContent.find_or_create_by! title: "Address", description: "Lorem Ipsum is simply dummy text.", slug: "addresses-main-heading-desc"
Spree::PageContent.find_or_create_by! title: "Add New", description: "", slug: "address-btn-label-new"
Spree::PageContent.find_or_create_by! title: "Primary Address", description: "", slug: "address-primary-heading"
Spree::PageContent.find_or_create_by! title: "Address", description: "", slug: "address-existing-heading"

Spree::PageContent.find_or_create_by! title: "Contact Name", description: "", slug: "address-field-label-contact-name"
Spree::PageContent.find_or_create_by! title: "Contact Name can't be blank", description: "", slug: "address-error-msg-contact-name"
Spree::PageContent.find_or_create_by! title: "Contact Number", description: "", slug: "address-field-label-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number can't be blank", description: "", slug: "address-error-msg-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number is not valid", description: "", slug: "address-error-msg-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "Street Address Line 1", description: "", slug: "address-field-label-address-1"
Spree::PageContent.find_or_create_by! title: "Address Line 1 can't be blank", description: "", slug: "address-error-msg-address-1"
Spree::PageContent.find_or_create_by! title: "Street Address Line 2", description: "", slug: "address-field-label-address-2"
Spree::PageContent.find_or_create_by! title: "Street Address Line 3", description: "", slug: "address-field-label-address-3"
Spree::PageContent.find_or_create_by! title: "Town/Suburb", description: "", slug: "address-field-label-town"
Spree::PageContent.find_or_create_by! title: "Town/Suburb can't be blank", description: "", slug: "address-error-msg-town"
Spree::PageContent.find_or_create_by! title: "State/Province", description: "", slug: "address-field-label-state"
Spree::PageContent.find_or_create_by! title: "State/Province can't be blank", description: "", slug: "address-error-msg-satate"
Spree::PageContent.find_or_create_by! title: "Country ", description: "", slug: "address-field-label-country"
Spree::PageContent.find_or_create_by! title: "Country can't be blank", description: "", slug: "address-error-msg-country"
Spree::PageContent.find_or_create_by! title: "Save", description: "", slug: "address-btn-label-save"
Spree::PageContent.find_or_create_by! title: "Address successfully created", description: "", slug: "address-success-msg-save"
Spree::PageContent.find_or_create_by! title: "Primary", description: "", slug: "address-btn-label-primary"
Spree::PageContent.find_or_create_by! title: "Delete", description: "", slug: "address-btn-label-delete"
Spree::PageContent.find_or_create_by! title: "New Address", description: "", slug: "address-new-address-heading"
Spree::PageContent.find_or_create_by! title: "New Contact Name", description: "", slug: "address-field-label-new-contact-name"
Spree::PageContent.find_or_create_by! title: "New Contact Name can't be blank", description: "", slug: "address-error-msg-new-contact-name"
Spree::PageContent.find_or_create_by! title: "New Contact Number", description: "", slug: "address-field-label-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number can't be blank", description: "", slug: "address-error-msg-new-contact-number"
Spree::PageContent.find_or_create_by! title: "Contact Number is not valid", description: "", slug: "address-error-msg-new-contact-number-formate"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 1", description: "", slug: "address-field-label-new-address-1"
Spree::PageContent.find_or_create_by! title: "New Address Line 1 can't be blank", description: "", slug: "address-error-msg-new-address-1"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 2", description: "", slug: "address-field-label-new-address-2"
Spree::PageContent.find_or_create_by! title: "New Street Address Line 3", description: "", slug: "address-field-label-new-address-3"
Spree::PageContent.find_or_create_by! title: "New Town/Suburb", description: "", slug: "address-field-label-new-town"
Spree::PageContent.find_or_create_by! title: "New Town/Suburb can't be blank", description: "", slug: "address-error-msg-new-town"
Spree::PageContent.find_or_create_by! title: "New State/Province", description: "", slug: "address-field-label-new-state"
Spree::PageContent.find_or_create_by! title: "New State/Province can't be blank", description: "", slug: "address-error-msg-new-satate"
Spree::PageContent.find_or_create_by! title: "New Country ", description: "", slug: "address-field-label-new-country"
Spree::PageContent.find_or_create_by! title: "New Country can't be blank", description: "", slug: "address-error-msg-new-country"
Spree::PageContent.find_or_create_by! title: "New Save", description: "", slug: "address-btn-label-new-save"
Spree::PageContent.find_or_create_by! title: "Address successfully created", description: "", slug: "address-success-msg-new-save"


